name = "odnowakanapowa-frontend"
compatibility_date = "2024-10-25"

# Pages configuration
pages_build_output_dir = "dist"

[env.production]
name = "odnowakanapowa-frontend-git"

[env.development]
name = "odnowakanapowa-frontend-dev"