name = "ok-backend"
main = "src/index.ts"
compatibility_date = "2024-10-25"
compatibility_flags = ["nodejs_compat"]

# Production environment (default for auto-deployment)
route = { pattern = "api.odnowakanapowa.pl/*", zone_name = "odnowakanapowa.pl" }

# GitHub integration
[triggers]
crons = []

[build]
command = ""

[vars]
ENVIRONMENT = "production"
JWT_SECRET = "e6773055dac6000e87870df47eb3e7bff8a030fb1f03d2c933e23bcc125d4c5a72e52a261ffe695c308b55d1b3b86a0b4e5116b358d554afb32c6f2428f27988"

[[d1_databases]]
binding = "DB"
database_name = "odnowa-kanapowa-db"
database_id = "224216c4-7a70-4ce7-999a-84e84b77b294"

[env.development]
name = "ok-backend-dev"

[env.development.vars]
ENVIRONMENT = "development"
JWT_SECRET = "e6773055dac6000e87870df47eb3e7bff8a030fb1f03d2c933e23bcc125d4c5a72e52a261ffe695c308b55d1b3b86a0b4e5116b358d554afb32c6f2428f27988"

[[env.development.d1_databases]]
binding = "DB"
database_name = "odnowa-kanapowa-db"
database_id = "224216c4-7a70-4ce7-999a-84e84b77b294"